users/urls.py
from . import views
from django.urls import path

app_name='users'
urlpatterns = [
    path('teachers', views.teacherslist, name='teachers_list'),
    path('students', views.studentlist, name='student_list'),
    path('teacher/<int:pk>', views.teacherdetail, name='teacher_detail'),
    path('', views.home, name='home'),
    path('<pk>/delete', views.delete_teacher, name= 'delete_teacher' ), 
    path('<pk>/delete', views.delete_student, name= 'delete_student' ), 

]

zetamind/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from model_utils import Choices


# CLASS = (
#     ("JSS1","Jss1"),
#     ("JSS2","Jss2"),
#     ("JSS3","Jss3"),
#     ("SSS1","Sss1"),
#     ("SSS2","Sss2"),
#     ("SSS3","Sss3"),
# )

class Teacher(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    level=models.IntegerField()
    CLASS = Choices('Jss1', 'Jss2', 'Jss3', 'Sss1', 'Sss2', 'Sss3')
    class_held = models.CharField(max_length=5 , choices=CLASS)

    def __str__(self):
        return self.first_name+" "+ self.last_name

class Student(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    class_in = models.CharField(max_length=5)
    teacher =models.ForeignKey(Teacher, blank=True, null=True, related_name='students', on_delete=models.SET_NULL)


    class Meta:
        ordering = ['-class_in']

    def __str__(self):
        return self.first_name+ " " +self.last_name

users/forms.py
from django import forms
from .models import Teacher,Student

class TeacherForm(forms.ModelForm):

    class Meta:
        model = Teacher
        fields = ['first_name', 'last_name', 'level', 'class_held']


        


class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'teacher']


        

# class StudentForm(forms.ModelForm):

#     class Meta:
#         model = Student
#         fields = ['first_name', 'last_name', 'class_in']


        

users/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from .models import Teacher,Student
from .forms import TeacherForm, StudentForm

def home(request):
    return render(request, 'home.html')

def teacherslist(request):
    teachers=Teacher.objects.all()
    if request.method == 'POST':
        form = TeacherForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            print(form.errors)
    else:
        form=TeacherForm()

    return render(request, 'teachers.html', {'teachers': teachers, 'form':form})




def studentlist(request):
    student = Student.objects.all()
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            studentz=form.save(commit=False)
            studentz.class_in=studentz.teacher.class_held
            studentz.save()
            print('formsaved')

        else:
            print(form.errors)
    else:
        form=StudentForm()

    return render(request, 'students.html', {'student': student, 'form':form})

# def studentlist(request):
#     student = Student.objects.all()
#     teacher =get_object_or_404(Teacher, class_held=class_held)
#     if request.method == 'POST':
#         form = StudentForm(request.POST)
#         if form.is_valid():
#             studentz=form.save(commit=False)
#             studentz.teacher=studentz.class_in.class_held
#             studentz.save()
#             print('formsaved')

#         else:
#             print(form.errors)
#     else:
#         form=StudentForm()

#     return render(request, 'students.html', {'student': student, 'form':form})



def teacherdetail(request, pk):
    teacher = get_object_or_404(Teacher, pk=pk)
    mystudents = teacher.students.all()
    return render(request, 'teachetdetails.html', {'mystudents': mystudents, 'teacher':teacher})


def delete_teacher(request, pk): 
 
    context ={} 
    obj = get_object_or_404(Teacher, pk = pk) 
  
  
    if request.method =="POST": 
        obj.delete() 
        return HttpResponseRedirect("/teachers") 
  
    return render(request, "delete_view.html", context) 

def delete_student(request, pk): 
 
    context ={} 
    obj = get_object_or_404(Student, pk = pk) 
  
  
    if request.method =="POST": 
        obj.delete() 
        return HttpResponseRedirect("/students") 
  
    return render(request, "delete_view.html", context) 

def man (request):
    pass

templates/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}
      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
       <link href="{% static 'static/css/style.css' %}" rel="stylesheet">

</head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top" id="banner">
      <div class="container">
      <!-- Brand -->
      <a class="navbar-brand" href="{% url 'users:home' %}"><span>Contonso College</span></a>
    
      <!-- Toggler/collapsibe Button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <!-- Navbar links -->
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:teachers_list' %}">Teachers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:student_list' %}">Students</a>
          </li>
         <!-- Dropdown -->
        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            Dropdown link
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Link 1</a>
            <a class="dropdown-item" href="#">Link 2</a>
            <a class="dropdown-item" href="#">Link 3</a>
          </div>
        </li> -->
        </ul>
      </div>
      </div>
    </nav>
<br><br>


<div class="container">
<br><br>
      {% block content %}
      {% endblock %}
</div>
</body>

</html>

templates/delete_view.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
All Teachers
{% endblock %}



{% block content %}
<div class="main"> 
    <!-- Create a Form -->
    <form method="POST"> 
        <!-- Security token by Django -->
        {% csrf_token %} 
        Are you want to delete this item ? 
        <input type="submit" value="Yes" /> 
        <a href="/">Cancel </a> 
    </form> 
</div> 

{% endblock %}

templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
   <!-- Basic -->
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <!-- Mobile Metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <!-- Site Metas -->
   <title>contonso Home</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">
   <!-- site icon -->
   <!-- Bootstrap core CSS -->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      <link href="{% static 'static/css/style.css' %}" rel="stylesheet">

   <link href="{% static 'static/css/style.css' %}" rel="stylesheet">

</head>
<body id="home_page" class="home_page">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top" id="banner">
        <div class="container">
        <!-- Brand -->
        <a class="navbar-brand" href="{% url 'users:home' %}"><span>Contonso College</span></a>
      
        <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <!-- Navbar links -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:teachers_list' %}">Teachers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:student_list' %}">Students</a>
            </li>
           <!-- Dropdown -->
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
              Dropdown link
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="#">Link 1</a>
              <a class="dropdown-item" href="#">Link 2</a>
              <a class="dropdown-item" href="#">Link 3</a>
            </div>
          </li> -->
          </ul>
        </div>
        </div>
      </nav>
  <br><br>

   <!-- end header -->
   
   <!-- section -->
   <section class="main_full banner_section_top">
     <div class="container-fluid">
       <div class="row">
          <div class="full">
               <div class="slider_banner">
                 <img class="img-responsive" src="https://i.ibb.co/HCn6W0k/home.jpg" alt="#" />
                   <div class="slide_cont">
                     <div class="slider_cont_inner">
                       <h3 style="color: black;">Welcome To Our school's</h3>
                       <br>
                       <h3 style="color: black;">management System</h3>
                     <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit</p> -->
                     <a class="blue_bt" href="#">Read More</a>
                     </div>
                   </div>
               </div>
             </div>
       </div>
     </div>
   </section>
   <!-- end section -->
<!--  
https://i.ibb.co/HCn6W0k/home.jpg
-->
   <!-- section -->
   <section class="layout_padding section">
      <div class="container">
         <div class="row">
            <div class="col-lg-12 text_align_center">
               <div class="full heading_s1">
                  <!-- <h2>Our Courses</h2> -->
               </div>
               <div class="full">
                  <!-- <p class="large">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo</p> -->
               </div>
            </div>
         </div>
         <div class="row">

           <div class="col-md-6 text_align_center">
              <div class="cours">
                <img class="img-responsive" src="https://i.ibb.co/fqXmQbm/teacher.jpg " alt="#" />
              </div><br>
              <a href="{% url 'users:teachers_list' %}">
                  <button class="btn btn-primary">
                      view Teachers
                  </button>
              </a>
              <!-- <p>adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in re</p> -->
           </div>  

           <div class="col-md-6 text_align_center">
              <div class="cours">
                <img class="img-responsive" src="https://i.ibb.co/nMSqh2b/student.jpg" alt="#" />
              </div>
              <br>
              <a href="{% url 'users:student_list' %}">
                  <button class="btn btn-primary">
                      view students
                  </button>
              </a>
              <!-- <p>adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in re</p> -->
           </div> 



         </div>
         
      </div>
   </section>
   <!-- end section -->



 

  
   <!-- footer -->
   <footer class="footer layout_padding">
      <div class="container">
         <div class="row">

            <div class="col-md-4 col-sm-12">
               <a href="index.html"><img class="img-responsive" src="images/logo_footer.png" alt="#" /></a>
               <div class="footer_link_heading">
                  <div class="footer_menu margin_top_30">
                  <ul>
                     <li><a href="tel:9876543210">9876 543 210</a></li>
                     <li><a href="#">demo@gmail.com</a></li>
                     <li><a href="#">40 Baria Sreet 133/2 NewYork City, US</a></li>
                  </ul>
               </div>
               </div>
            </div>
            
            <div class="col-md-8">
              <div class="row">
                 <div class="col-md-4 col-sm-12">
               <div class="footer_link_heading">
                  <h3>FEATURED COURSES</h3>
               </div>
               <div class="footer_menu">
                  <ul>
                     <li><a href="#">Starting Soon</a></li>
                     <li><a href="#">Just Added</a></li>
                     <li><a href="#">Most Viewed</a></li>
                     <li><a href="#">Top Paid</a></li>
                  </ul>
               </div>
            </div>

            <div class="col-md-4 col-sm-12">
               <div class="footer_link_heading">
                  <h3>CATEGORIES</h3>
               </div>
               <div class="footer_menu">
                 <ul>
                    <li><a href="#">Arts & Design</a></li>
                    <li><a href="#">Business</a></li>
                    <li><a href="#">Computer</a></li>
                    <li><a href="#">Data entery</a></li>
                 </ul>
               </div>
            </div>
            
            <div class="col-md-4 col-sm-12">
               <div class="footer_link_heading">
                  <h3>USEFUL LINKS</h3>
               </div>
               <div class="footer_menu">
                 <ul>
                    <li><a href="#">FAQs</a></li>
                    <li><a href="#">Success Stories</a></li>
                    <li><a href="#">Shop</a></li>
                    <li><a href="#">Privacy policy</a></li>
                    <li><a href="#">Contact search</a></li>
                    <li><a href="#">Jobs and vacancies</a></li>
                 </ul>
               </div>
            </div>
              </div>
            </div>
            
         </div>
      </div>
   </footer>


</body>
</html>

templates/students.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block breadcrumb %}
<li class="breadcrumb-item active"><a href="{% url 'users:home' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'users:student_list' %}">students</a></li>
{% endblock %}



{% block content %}
    <div class="row">
        <div class="col-md 8">
            <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">Student No</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Class </th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                {% for s in student %}
        
                  <tr>
                    <td>stud {{s.pk | stringformat:"03d"}}</td>
                    <td>{{s.first_name}}</td>
                    <td>{{s.last_name}}</td>
                    <td> {{s.class_in}}</td>
                    <td>
                      <!-- <a href="{% url 'users:delete_student' s.pk %}">
                        <button class="btn btn-danger btn-sm">
                          delete Student
                        </button>
                      </a> -->
                    </td>
 
                  </tr>
                {% endfor %} 
        
                </tbody>
              </table> 
        </div>
        <div class="col-md-4">
            <form method="post" novalidate>
                {% csrf_token %}
              
                {% for field in form %}
                  <div class="form-group">
                    {{ field.label_tag }}
              
                    {% if form.is_bound %}
                      {% if field.errors %}
              
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                          <div class="invalid-feedback">
                            {{ error }}
                          </div>
                        {% endfor %}
              
                      {% else %}
                        {% render_field field class="form-control is-valid" %}
                      {% endif %}
                    {% else %}
                      {% render_field field class="form-control" %}
                    {% endif %}
              
                    {% if field.help_text %}
                      <small class="form-text text-muted">
                        {{ field.help_text }}
                      </small>
                    {% endif %}
                  </div>
                {% endfor %}
              
                <button type="submit" class="btn btn-success">Post</button>
              </form>
        </div>
    </div>
      {% endblock %}

templates/teachers.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
All Teachers
{% endblock %}



{% block content %}
    <div class="row">
        <div class="col-md 8">
            <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">Staff No</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Levels</th>
                    <th scope="col">Class Held</th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                {% for t in teachers %}
                <tr>
                    <td>staffno {{t.pk | stringformat:"03d"}}</td>
                    <td>{{t.first_name}}</td>
                    <td>{{t.last_name}}</td>
                    <td>Level {{t.level}}</td>
                    <td>
                        {{t.class_held}}
                    </td>   
                    <td>
                      <a href="{% url 'users:teacher_detail' t.pk %}">
                        <button class="btn btn-primary btn-sm">
                          View Teacher
                        </button>
                      </a>
                    </td>

                    <td>
                      <a href="{% url 'users:delete_teacher' t.pk %}">
                        <button class="btn btn-danger btn-sm">
                          delete Teacher
                        </button>
                      </a>
                    </td>
                  </tr>
                {% endfor %} 
        
                </tbody>
              </table> 
        </div>
        <div class="col-md-4">
            <form method="post" novalidate>
                {% csrf_token %}
              
                {% for field in form %}
                  <div class="form-group">
                    {{ field.label_tag }}
              
                    {% if form.is_bound %}
                      {% if field.errors %}
              
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                          <div class="invalid-feedback">
                            {{ error }}
                          </div>
                        {% endfor %}
              
                      {% else %}
                        {% render_field field class="form-control is-valid" %}
                      {% endif %}
                    {% else %}
                      {% render_field field class="form-control" %}
                    {% endif %}
              
                    {% if field.help_text %}
                      <small class="form-text text-muted">
                        {{ field.help_text }}
                      </small>
                    {% endif %}
                  </div>
                {% endfor %}
              
                <button type="submit" class="btn btn-success">Post</button>
              </form>
        </div>
    </div>
      {% endblock %}

templates/teachetdetails.html
{% extends 'base.html' %}


{% block title %}
{{teacher.first_name}} {{teacher.last_name}}

{% endblock %}



{% block content %}
    <div class="row">
        <div class="col-md 8">
            <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">Student No</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Class </th>
                  </tr>
                </thead>
                <tbody>
                {% for ms in mystudents %}
        
                  <tr>
                    <td>stud {{ms.pk | stringformat:"03d"}}</td>
                    <td>{{ms.first_name}}</td>
                    <td>{{ms.last_name}}</td>
                    <td>{{ms.class_in}}</td>
    
                  </tr>
                {% endfor %} 
        
                </tbody>
              </table> 
        </div>
        <div class="col-md-4">
            
            
            <div class="card mb-2 {% if forloop.first %}border-dark{% endif %}">
                  <div class="card-header text-white bg-dark py-2 px-3">{{teacher.first_name}} {{teacher.last_name}}</div>

                  <div class="card-body p-3">
                    <div>                
                           <h2 class="text-bold">
                            Staff No <span style="font-size: 21px;">: {{teacher.pk | stringformat:"03d"}}</span>
                           </h2>

                    </div>
                    <div>
                        <h4 class="text-bold">
                            Staff Level <span style="font-size: 21px;"> :Level {{teacher.level}}</span>
                           </h4>
                    

                    </div>

                    <div>
                        <h4 class="text-bold">
                            Staff Class <span style="font-size: 21px;"> : {{teacher.class_held}}</span>
                           </h4>
                    

                    </div>
                </div>
              </div>
        </div>
    </div>
      {% endblock %}